name: mercuriongroup
favicon: null
layout_spectrum: 0.7653886855114251
typography_spectrum: 0.60763
title: Welcome to the Mercurion Group
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#682b0c'
    - '#b96c52'
    - '#5f6d70'
    - '#7cafee'
    - '#ddfbfd'
  brandStrength: 0.059339771745726466
  lightness: 0.6707468775566667
  saturation: 0.5
  rhythmicContrast: 0.7457856275141239
purpose: []
